# Generated by Django 5.2.12 on 2026-03-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_level_alter_category_lft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='invite_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
