server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location /media/ {
    return 404;
  }

  add_header X-Forwarded-Host $host;
  add_header X-Forwarded-Proto $scheme;

  location / {
    try_files $uri $uri/ /index.html;
  }
}